### PR TITLE
Images are now accessible in uploading documents activity.

### PR DESCRIPTION
**Pull request by soCallmeAdityaKumar**

### CODE REVIEW

**Comment by AnshTandon0** [comment]
Don't replace it . We need to have both features side by side . So create a complete UI and feature in which both images and pdf can be added as per requirement .

**Comment by Tarun-108** [comment]
@soCallmeAdityaKumar 
The documents can be of any file format it can be image or pdf. The application needs to support both file formats, previously it is supporting only pdfs. Need to support both types of file formats. 
So work accordingly.

**Comment by soCallmeAdityaKumar** [comment]
Do i need to add some more button/cardview to upload pdf and images file separately or both should be uploaded from the same cardview(depending on user whether he/she want to select image or pdf file)?

**Comment by Tarun-108** [comment]
@soCallmeAdityaKumar You don't need to change the flow of the app just make changes so that all the file formats (including jpg, png, jpeg, etc.) would be accessible.
No need to add any extra views.

**Comment by AnshTandon0** [comment]
Send screenshots of new UI @soCallmeAdityaKumar

**Comment by soCallmeAdityaKumar** [comment]
New Ui
Screenshot (351)

**Comment by AnshTandon0** [comment]
Completed by @soCallmeAdityaKumar

**Pull request merged**
