### PR TITLE
improved UI of Reminder Page & back button of Reminder Page is fixed.

### PR DESCRIPTION
**Pull request by savitore**

### CODE REVIEW

**Comment by AnshTandon0** [comment]
provide the images of new UI

**Comment by savitore** [comment]
send_reminder

**Comment by AnshTandon0** [comment]
increase text size in the button and make the corners round

**Comment by savitore** [comment]
send_reminder

Done.

**Comment by Tarun-108** [comment]
The button color is not matching the color scheme of the application. Also, go through the application flow and work on improving the UI accordingly (maybe some fields are unnecessary or some extra fields are needed).

**Comment by savitore** [comment]
send_reminder

Please review this.

**Pull request merged**
